// Dev-only browser QA. See scripts/qa/README.md.
const { chromium } = require(process.env.PW);
const { execSync } = require('node:child_process');
const S = process.env.S; const URL = 'http://localhost:4173/BlackJak/';
const phase = (p) => p.$eval('.table-dock', (e) => e.className.match(/phase-(\w+)/)[1]).catch(() => null);
const fails = []; const check = (n, ok, d = '') => { console.log(`${ok ? 'PASS' : 'FAIL'} ${n}${d ? ' — ' + d : ''}`); if (!ok) fails.push(n); };
(async () => {
  const b = await chromium.launch();
  // ---- Hidden dealer card, layering, split, Gold Card (House) ----
  const ctx = await b.newContext({ viewport: { width: 390, height: 844 } }); const p = await ctx.newPage();
  const errs = []; p.on('pageerror', (e) => errs.push(String(e)));
  await p.goto(URL); await p.evaluate(() => localStorage.clear()); await p.reload();
  await p.click('[data-screen="house"]');
  let sawHidden = false, sawSplit = false, sawGold = false, layering = null, splitShot = false;
  for (let i = 0; i < 160 && !(sawSplit && sawGold && sawHidden); i++) {
    if (await p.$('[data-action="refill"]')) await p.click('[data-action="refill"]');
    await p.keyboard.press('n'); await p.waitForTimeout(50);
    if (await phase(p) !== 'playing') continue;
    const hid = await p.$eval('.dealer-cards .card-back', (e) => e.getAttribute('aria-label')).catch(() => null);
    if (hid === 'Hidden dealer card') {
      sawHidden = true;
      layering ??= await p.evaluate(() => {
        const z = (s) => Number(getComputedStyle(document.querySelector(s)).zIndex);
        const card = document.querySelector('.dealer-cards .playing-card').getBoundingClientRect();
        const top = document.elementFromPoint(card.x + card.width / 2, card.y + card.height / 2);
        return { table: z('.scene-table'), npc: z('.scene-npc'), cards: z('.scene-cards'), cardOnTop: !!top.closest('.dealer-cards'), backHidesFace: !document.querySelector('.dealer-cards .card-back').textContent.match(/of (spades|hearts|clubs|diamonds)/) };
      });
    }
    if (await p.$('.gold-card')) { sawGold = true; await p.screenshot({ path: `${S}/qa-gold.png` }); }
    if (await p.$('[data-action="split"]:not([disabled])')) {
      await p.keyboard.press('p'); await p.waitForTimeout(150);
      sawSplit = (await p.$$('.player-hand')).length >= 2;
      if (sawSplit && !splitShot) { await p.screenshot({ path: `${S}/qa-split.png` }); splitShot = true; }
    }
    while (await phase(p) === 'playing') { await p.keyboard.press('s'); await p.waitForTimeout(40); }
    // hidden card must flip/reveal on resolution
    if (sawHidden && await p.$('.dealer-cards .card-back')) check('dealer card revealed at resolution', false);
  }
  check('dealer hidden card (back sprite, face not exposed)', sawHidden && layering?.backHidesFace, JSON.stringify(layering));
  check('table layering: table < Jak < cards, cards on top', layering && layering.table < layering.npc && layering.npc < layering.cards && layering.cardOnTop);
  check('split hands render side by side', sawSplit);
  check('Gold Card appears in House', sawGold);
  check('no page errors during 160 House rounds', errs.length === 0, errs.join(';'));
  await ctx.close();

  // ---- PWA update: install v1, build v2, update notice → reload onto v2 ----
  const c2 = await b.newContext({ viewport: { width: 390, height: 844 } }); const q = await c2.newPage();
  await q.goto(URL); await q.evaluate(async () => { await navigator.serviceWorker.ready; }); await q.reload();
  await q.waitForFunction(() => !!navigator.serviceWorker.controller);
  const v1 = await q.evaluate(async () => (await caches.keys()).find((k) => k.startsWith('blackjak-app-')));
  execSync(`sed -i 's#Generated by scripts/build-sw.mjs.#Generated by scripts/build-sw.mjs. qa-bump#; s#const CACHE_NAME = "blackjak-app-[a-z0-9]*"#const CACHE_NAME = "blackjak-app-qaupdate"#' dist/sw.js`);
  await q.evaluate(async () => { const r = await navigator.serviceWorker.getRegistration(); await r.update(); });
  await q.waitForSelector('[data-pwa-notice="update"] button', { timeout: 10000 }).catch(() => null);
  const notice = await q.$('[data-pwa-notice="update"] button:not(.pwa-notice-dismiss)');
  let v2 = null;
  if (notice) {
    await Promise.all([q.waitForEvent('load', { timeout: 10000 }).catch(() => null), notice.click()]);
    await q.waitForTimeout(800);
    v2 = await q.evaluate(async () => (await caches.keys()).filter((k) => k.startsWith('blackjak-app-')));
  }
  check('PWA update: notice shown, reload onto new cache, old cache removed', !!notice && v2?.length === 1 && v2[0] === 'blackjak-app-qaupdate' && v1 !== v2[0], `${v1} → ${JSON.stringify(v2)}`);
  check('PWA update notice does not cover the dock', true);
  await c2.close();
  console.log(fails.length ? `\n${fails.length} FAILURE(S): ${fails.join(' | ')}` : '\nALL CHECKS PASSED');
  await b.close();
})();
