import { createHash } from 'node:crypto';
import { readdir, readFile, writeFile } from 'node:fs/promises';
import { extname, join, relative, sep } from 'node:path';
import { fileURLToPath } from 'node:url';

const DIST_URL = new URL('../dist/', import.meta.url);
const DIST = fileURLToPath(DIST_URL);
const BASE = '/BlackJak/';
const APP_CACHE_PREFIX = 'blackjak-app-';
const MEDIA_CACHE_PREFIX = 'blackjak-media-';
// Media files are content-hashed, so one stable cache survives app updates;
// entries for files a build no longer ships are pruned on activate.
const MEDIA_CACHE_NAME = `${MEDIA_CACHE_PREFIX}v1`;
const MEDIA_EXTENSIONS = new Set(['.mp3', '.mp4', '.ogg', '.wav', '.webm']);

async function walk(directory) {
  const entries = await readdir(directory, { withFileTypes: true });
  const files = [];

  for (const entry of entries) {
    const absolute = join(directory, entry.name);
    if (entry.isDirectory()) files.push(...await walk(absolute));
    else if (entry.isFile() && entry.name !== 'sw.js') files.push(absolute);
  }

  return files;
}

const files = (await walk(DIST)).sort();
const hash = createHash('sha256');
const relativeFiles = [];

for (const file of files) {
  const rel = relative(DIST, file).split(sep).join('/');
  relativeFiles.push(rel);
  hash.update(rel);
  hash.update(await readFile(file));
}

const buildId = hash.digest('hex').slice(0, 12);
const appCacheName = `${APP_CACHE_PREFIX}${buildId}`;
const isMedia = (file) => MEDIA_EXTENSIONS.has(extname(file).toLowerCase());
const mediaUrls = relativeFiles.filter(isMedia).map((file) => `${BASE}${file}`);
const precacheUrls = Array.from(new Set([
  BASE,
  ...relativeFiles.filter((file) => !isMedia(file)).map((file) => `${BASE}${file}`),
]));

for (const url of [...precacheUrls, ...mediaUrls]) {
  // Cache keys are compared by pathname; an unsafe character would need encoding.
  if (!/^[\w./-]+$/.test(url)) throw new Error(`build-sw: asset URL is not URL-safe: ${url}`);
}

const source = `/* Generated by scripts/build-sw.mjs. Do not edit dist/sw.js directly. */
const APP_CACHE_NAME = ${JSON.stringify(appCacheName)};
const APP_CACHE_PREFIX = ${JSON.stringify(APP_CACHE_PREFIX)};
const MEDIA_CACHE_NAME = ${JSON.stringify(MEDIA_CACHE_NAME)};
const MEDIA_CACHE_PREFIX = ${JSON.stringify(MEDIA_CACHE_PREFIX)};
const BASE_PATH = ${JSON.stringify(BASE)};
// Core app shell + art: precached so install means "playable offline".
const PRECACHE_URLS = ${JSON.stringify(precacheUrls, null, 2)};
// Intro video + music: runtime-cached on first use. They are large, optional,
// and must never be able to fail the install.
const MEDIA_URLS = ${JSON.stringify(mediaUrls, null, 2)};
const MEDIA_PATHS = new Set(MEDIA_URLS);

self.addEventListener('install', (event) => {
  event.waitUntil(
    caches.open(APP_CACHE_NAME).then((cache) => cache.addAll(PRECACHE_URLS))
  );
});

async function pruneMediaCache() {
  const cache = await caches.open(MEDIA_CACHE_NAME);
  const keys = await cache.keys();
  await Promise.all(keys
    .filter((request) => !MEDIA_PATHS.has(new URL(request.url).pathname))
    .map((request) => cache.delete(request)));
}

self.addEventListener('activate', (event) => {
  event.waitUntil(
    Promise.all([
      caches.keys().then((keys) =>
        Promise.all(
          keys
            .filter((key) =>
              (key.startsWith(APP_CACHE_PREFIX) && key !== APP_CACHE_NAME) ||
              (key.startsWith(MEDIA_CACHE_PREFIX) && key !== MEDIA_CACHE_NAME)
            )
            .map((key) => caches.delete(key))
        )
      ),
      pruneMediaCache().catch(() => undefined),
      self.clients.claim(),
    ])
  );
});

self.addEventListener('message', (event) => {
  if (event.data?.type === 'SKIP_WAITING') self.skipWaiting();
});

// Media elements issue HTTP Range requests (and Safari requires 206 answers),
// so cached files are sliced into partial responses. Blob.slice avoids copying.
async function rangeResponse(request, response) {
  const range = request.headers.get('range');
  if (!range) return response;

  const match = /^bytes=(\\d*)-(\\d*)$/i.exec(range.trim());
  if (!match || (!match[1] && !match[2])) return response;

  const blob = await response.blob();
  const size = blob.size;
  let start;
  let end;
  if (!match[1]) {
    start = Math.max(0, size - Number(match[2]));
    end = size - 1;
  } else {
    start = Number(match[1]);
    end = match[2] ? Math.min(Number(match[2]), size - 1) : size - 1;
  }

  if (start >= size || end < start) {
    return new Response(null, { status: 416, headers: { 'Content-Range': 'bytes */' + size } });
  }

  const headers = new Headers(response.headers);
  headers.set('Accept-Ranges', 'bytes');
  headers.set('Content-Range', 'bytes ' + start + '-' + end + '/' + size);
  headers.set('Content-Length', String(end - start + 1));
  return new Response(blob.slice(start, end + 1), { status: 206, statusText: 'Partial Content', headers });
}

// A media element fires several Range requests at once; fetch each file once.
const mediaDownloads = new Map();

function downloadMedia(key) {
  let pending = mediaDownloads.get(key);
  if (!pending) {
    pending = fetch(key, { credentials: 'same-origin' })
      .then(async (response) => {
        if (response.status !== 200) return null;
        const cache = await caches.open(MEDIA_CACHE_NAME);
        await cache.put(key, response.clone()).catch(() => undefined);
        return response;
      })
      .finally(() => mediaDownloads.delete(key));
    mediaDownloads.set(key, pending);
  }
  return pending.then((response) => response && response.clone());
}

async function runtimeMedia(request, key) {
  const cache = await caches.open(MEDIA_CACHE_NAME);
  const cached = await cache.match(key);
  if (cached) return rangeResponse(request, cached);

  try {
    const full = await downloadMedia(key);
    if (full) return rangeResponse(request, full);
  } catch {
    // Offline and not cached yet: fall through to a network error, which the
    // intro/music code treats as "skip this media", never as a startup failure.
  }
  return fetch(request).catch(() => Response.error());
}

self.addEventListener('fetch', (event) => {
  const request = event.request;
  if (request.method !== 'GET') return;

  const url = new URL(request.url);
  if (url.origin !== self.location.origin || !url.pathname.startsWith(BASE_PATH)) return;

  if (MEDIA_PATHS.has(url.pathname)) {
    event.respondWith(runtimeMedia(request, url.origin + url.pathname));
    return;
  }

  if (request.mode === 'navigate') {
    event.respondWith(
      fetch(request)
        .then((response) => {
          if (response.ok) {
            const copy = response.clone();
            caches.open(APP_CACHE_NAME).then((cache) => cache.put(request, copy)).catch(() => undefined);
          }
          return response;
        })
        .catch(async () => {
          const cache = await caches.open(APP_CACHE_NAME);
          return (
            await cache.match(request, { ignoreSearch: true }) ||
            await cache.match(BASE_PATH) ||
            await cache.match(BASE_PATH + 'index.html') ||
            Response.error()
          );
        })
    );
    return;
  }

  event.respondWith(
    caches.match(request, { ignoreSearch: true }).then((cached) => {
      if (cached) return cached;

      return fetch(request).then((response) => {
        if (response.status === 200) {
          const copy = response.clone();
          caches.open(APP_CACHE_NAME).then((cache) => cache.put(request, copy)).catch(() => undefined);
        }
        return response;
      });
    })
  );
});
`;

await writeFile(new URL('../dist/sw.js', import.meta.url), source);
console.log(
  `Generated service worker ${appCacheName}: ${precacheUrls.length} core URLs precached; ${mediaUrls.length} media files runtime-cached in ${MEDIA_CACHE_NAME}.`,
);
