import { createHash } from 'node:crypto';
import { readdir, readFile, writeFile } from 'node:fs/promises';
import { join, relative, sep } from 'node:path';
import { fileURLToPath } from 'node:url';

const DIST_URL = new URL('../dist/', import.meta.url);
const DIST = fileURLToPath(DIST_URL);
const BASE = '/BlackJak/';
const CACHE_PREFIX = 'blackjak-app-';

async function walk(directory) {
  const entries = await readdir(directory, { withFileTypes: true });
  const files = [];

  for (const entry of entries) {
    const absolute = join(directory, entry.name);
    if (entry.isDirectory()) {
      files.push(...await walk(absolute));
    } else if (entry.isFile() && entry.name !== 'sw.js') {
      files.push(absolute);
    }
  }

  return files;
}

const files = (await walk(DIST)).sort();
const hash = createHash('sha256');
const relativeFiles = [];

for (const file of files) {
  const rel = relative(DIST, file).split(sep).join('/');
  relativeFiles.push(rel);
  hash.update(rel);
  hash.update(await readFile(file));
}

const buildId = hash.digest('hex').slice(0, 12);
const cacheName = `${CACHE_PREFIX}${buildId}`;
const precacheUrls = Array.from(new Set([
  BASE,
  ...relativeFiles.map((file) => `${BASE}${file}`),
]));

const source = `/* Generated by scripts/build-sw.mjs. Do not edit dist/sw.js directly. */
const CACHE_NAME = ${JSON.stringify(cacheName)};
const CACHE_PREFIX = ${JSON.stringify(CACHE_PREFIX)};
const BASE_PATH = ${JSON.stringify(BASE)};
const PRECACHE_URLS = ${JSON.stringify(precacheUrls, null, 2)};

self.addEventListener('install', (event) => {
  event.waitUntil(
    caches.open(CACHE_NAME).then((cache) => cache.addAll(PRECACHE_URLS))
  );
});

self.addEventListener('activate', (event) => {
  event.waitUntil(
    Promise.all([
      caches.keys().then((keys) =>
        Promise.all(
          keys
            .filter((key) => key.startsWith(CACHE_PREFIX) && key !== CACHE_NAME)
            .map((key) => caches.delete(key))
        )
      ),
      self.clients.claim(),
    ])
  );
});

self.addEventListener('message', (event) => {
  if (event.data?.type === 'SKIP_WAITING') self.skipWaiting();
});

self.addEventListener('fetch', (event) => {
  const request = event.request;
  if (request.method !== 'GET') return;

  const url = new URL(request.url);
  if (url.origin !== self.location.origin || !url.pathname.startsWith(BASE_PATH)) return;

  if (request.mode === 'navigate') {
    event.respondWith(
      fetch(request)
        .then((response) => {
          if (response.ok) {
            const copy = response.clone();
            caches.open(CACHE_NAME).then((cache) => cache.put(request, copy));
          }
          return response;
        })
        .catch(async () => {
          const cache = await caches.open(CACHE_NAME);
          return (
            await cache.match(request, { ignoreSearch: true }) ||
            await cache.match(BASE_PATH) ||
            await cache.match(`${BASE_PATH}index.html`) ||
            Response.error()
          );
        })
    );
    return;
  }

  event.respondWith(
    caches.match(request, { ignoreSearch: true }).then((cached) => {
      if (cached) return cached;

      return fetch(request).then((response) => {
        if (response.ok) {
          const copy = response.clone();
          caches.open(CACHE_NAME).then((cache) => cache.put(request, copy));
        }
        return response;
      });
    })
  );
});
`;

await writeFile(new URL('../dist/sw.js', import.meta.url), source);
console.log(`Generated service worker ${cacheName} with ${precacheUrls.length} precached URLs.`);
