import { createHash } from 'node:crypto';
import { readdir, readFile, writeFile } from 'node:fs/promises';
import { extname, join, relative, sep } from 'node:path';
import { fileURLToPath } from 'node:url';

const DIST_URL = new URL('../dist/', import.meta.url);
const DIST = fileURLToPath(DIST_URL);
const BASE = '/BlackJak/';
const APP_CACHE_PREFIX = 'blackjak-app-';
const MEDIA_CACHE_PREFIX = 'blackjak-media-';
const MEDIA_EXTENSIONS = new Set(['.mp3', '.mp4', '.ogg', '.wav', '.webm']);

async function walk(directory) {
  const entries = await readdir(directory, { withFileTypes: true });
  const files = [];

  for (const entry of entries) {
    const absolute = join(directory, entry.name);
    if (entry.isDirectory()) files.push(...await walk(absolute));
    else if (entry.isFile() && entry.name !== 'sw.js') files.push(absolute);
  }

  return files;
}

const files = (await walk(DIST)).sort();
const hash = createHash('sha256');
const relativeFiles = [];

for (const file of files) {
  const rel = relative(DIST, file).split(sep).join('/');
  relativeFiles.push(rel);
  hash.update(rel);
  hash.update(await readFile(file));
}

const buildId = hash.digest('hex').slice(0, 12);
const appCacheName = `${APP_CACHE_PREFIX}${buildId}`;
const mediaCacheName = `${MEDIA_CACHE_PREFIX}${buildId}`;
const mediaFiles = relativeFiles.filter((file) => MEDIA_EXTENSIONS.has(extname(file).toLowerCase()));
const precacheFiles = relativeFiles.filter((file) => !MEDIA_EXTENSIONS.has(extname(file).toLowerCase()));
const precacheUrls = Array.from(new Set([
  BASE,
  ...precacheFiles.map((file) => `${BASE}${file}`),
]));

const source = `/* Generated by scripts/build-sw.mjs. Do not edit dist/sw.js directly. */
const APP_CACHE_NAME = ${JSON.stringify(appCacheName)};
const MEDIA_CACHE_NAME = ${JSON.stringify(mediaCacheName)};
const APP_CACHE_PREFIX = ${JSON.stringify(APP_CACHE_PREFIX)};
const MEDIA_CACHE_PREFIX = ${JSON.stringify(MEDIA_CACHE_PREFIX)};
const BASE_PATH = ${JSON.stringify(BASE)};
const PRECACHE_URLS = ${JSON.stringify(precacheUrls, null, 2)};
const MEDIA_EXTENSIONS = /\\.(?:mp3|mp4|ogg|wav|webm)$/i;

self.addEventListener('install', (event) => {
  event.waitUntil(
    caches.open(APP_CACHE_NAME).then((cache) => cache.addAll(PRECACHE_URLS))
  );
});

self.addEventListener('activate', (event) => {
  event.waitUntil(
    Promise.all([
      caches.keys().then((keys) =>
        Promise.all(
          keys
            .filter((key) =>
              (key.startsWith(APP_CACHE_PREFIX) && key !== APP_CACHE_NAME) ||
              (key.startsWith(MEDIA_CACHE_PREFIX) && key !== MEDIA_CACHE_NAME)
            )
            .map((key) => caches.delete(key))
        )
      ),
      self.clients.claim(),
    ])
  );
});

self.addEventListener('message', (event) => {
  if (event.data?.type === 'SKIP_WAITING') self.skipWaiting();
});

async function rangeResponse(request, response) {
  const range = request.headers.get('range');
  if (!range) return response;

  const match = /^bytes=(\\d*)-(\\d*)$/i.exec(range.trim());
  if (!match) return response;

  const bytes = await response.arrayBuffer();
  const size = bytes.byteLength;
  let start = match[1] ? Number(match[1]) : 0;
  let end = match[2] ? Number(match[2]) : size - 1;

  if (!match[1] && match[2]) {
    const suffix = Number(match[2]);
    start = Math.max(0, size - suffix);
    end = size - 1;
  }

  if (!Number.isFinite(start) || !Number.isFinite(end) || start < 0 || start >= size || end < start) {
    return new Response(null, {
      status: 416,
      headers: { 'Content-Range': 'bytes */' + size },
    });
  }

  end = Math.min(end, size - 1);
  const headers = new Headers(response.headers);
  headers.set('Accept-Ranges', 'bytes');
  headers.set('Content-Range', 'bytes ' + start + '-' + end + '/' + size);
  headers.set('Content-Length', String(end - start + 1));

  return new Response(bytes.slice(start, end + 1), {
    status: 206,
    statusText: 'Partial Content',
    headers,
  });
}

async function runtimeMedia(request) {
  const cache = await caches.open(MEDIA_CACHE_NAME);
  const cacheKey = new Request(request.url, { method: 'GET' });
  const cached = await cache.match(cacheKey, { ignoreSearch: true });
  if (cached) return rangeResponse(request, cached);

  try {
    // A Range request cannot populate a reusable full-file cache. Fetch the
    // complete same-origin asset once, store it, then serve the requested bytes.
    const response = request.headers.has('range')
      ? await fetch(request.url, { credentials: 'same-origin' })
      : await fetch(request);

    if (response.ok && response.status === 200) {
      const full = response.clone();
      await cache.put(cacheKey, full.clone());
      return rangeResponse(request, full);
    }

    return response;
  } catch {
    const fallback = await cache.match(cacheKey, { ignoreSearch: true });
    return fallback ? rangeResponse(request, fallback) : Response.error();
  }
}

self.addEventListener('fetch', (event) => {
  const request = event.request;
  if (request.method !== 'GET') return;

  const url = new URL(request.url);
  if (url.origin !== self.location.origin || !url.pathname.startsWith(BASE_PATH)) return;

  if (MEDIA_EXTENSIONS.test(url.pathname)) {
    event.respondWith(runtimeMedia(request));
    return;
  }

  if (request.mode === 'navigate') {
    event.respondWith(
      fetch(request)
        .then((response) => {
          if (response.ok) {
            const copy = response.clone();
            caches.open(APP_CACHE_NAME).then((cache) => cache.put(request, copy));
          }
          return response;
        })
        .catch(async () => {
          const cache = await caches.open(APP_CACHE_NAME);
          return (
            await cache.match(request, { ignoreSearch: true }) ||
            await cache.match(BASE_PATH) ||
            await cache.match(BASE_PATH + 'index.html') ||
            Response.error()
          );
        })
    );
    return;
  }

  event.respondWith(
    caches.match(request, { ignoreSearch: true }).then((cached) => {
      if (cached) return cached;

      return fetch(request).then((response) => {
        if (response.ok) {
          const copy = response.clone();
          caches.open(APP_CACHE_NAME).then((cache) => cache.put(request, copy));
        }
        return response;
      });
    })
  );
});
`;

await writeFile(new URL('../dist/sw.js', import.meta.url), source);
console.log(
  `Generated service worker ${appCacheName} with ${precacheUrls.length} core URLs; ${mediaFiles.length} media files runtime-cached via ${mediaCacheName}.`,
);
